class NotFound(Exception):
    pass


class ResourceAlreadyExists(Exception):
    pass
